testing

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -31,8 +31,7 @@ jobs:
       - name: Run Hugo build with proper baseURL
         run: |
           docker compose run --no-deps --name hugo_builder hugo \
-            hugo --baseURL "https://garrett-kirsch.ceo" \
-                  --destination /home/personal_website/public
+            sh -c "hugo --baseURL 'https://garrett-kirsch.ceo' --destination /home/personal_website/public && grep -o 'in progress.*' /home/personal_website/public/index.html || echo 'NOT FOUND IN CONTAINER'"
       - name: Copy public/ from builder container
         run: |
           docker cp hugo_builder:/home/personal_website/public ./public
